apiVersion: apps/v1
kind: Deployment
metadata:
  name: SSSSSS
spec:
  template:
    spec:
      dnsPolicy: "ClusterFirst"
      dnsConfig:
        options:
          - name: ndots
            value: "2"