apiVersion: v1
kind: Service
metadata:
  name: SSSSSS
  namespace: dostyk
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: metric
  selector:
    service: SSSSSS
  type: ClusterIP
